document.write('    <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#B23737" width="100%" id="AutoNumber3">');
document.write('      <tr>');
document.write('        <td width="100%" align="center" background="file:///C:/Documents%20and%20Settings/Chris/My%20Documents/My%20Webs/tsnII/images/r_table_head.jpg" height="28">');
document.write('        <b><font face="Trebuchet MS" size="2" color="#FFFFFF">Image Gallery</font></b></td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td width="100%" align="center"><b>');
document.write('        <a href="images.html#logos" style="text-decoration: none"><font face="Trebuchet MS" size="1" color="#B23737">Logos</font></a><br>');
document.write('        <a href="images.html#smiley" style="text-decoration: none"><font face="Trebuchet MS" size="1" color="#B23737">Smiles</font></a></b></td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td width="100%" align="center" background="file:///C:/Documents%20and%20Settings/Chris/My%20Documents/My%20Webs/tsnII/images/r_table_head.jpg" height="28">');
document.write('        <b><font face="Trebuchet MS" size="2" color="#FFFFFF">Products</font></b></td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td width="100%" align="center"><b>');
document.write('        <font face="Trebuchet MS" size="1" color="#B23737">');
document.write('        <a href="products.html#mensapperal" style="text-decoration: none">');
document.write('        <font color="#B23737">Men\'s Apparel</font></a><br>');
document.write('        <a href="products.html#womensapperal" style="text-decoration: none">');
document.write('        <font color="#B23737">Women\'s Apperal</font></a><br>');
document.write('        <a href="products.html#housewares" style="text-decoration: none">');
document.write('        <font color="#B23737">Housewares</font></a><br>');
document.write('        <a href="products.html#bags" style="text-decoration: none"><font color="#B23737">Bags</font></a></font></b></td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td width="100%" align="center" background="file:///C:/Documents%20and%20Settings/Chris/My%20Documents/My%20Webs/tsnII/images/r_table_head.jpg" height="28">');
document.write('        <b><font face="Trebuchet MS" size="2" color="#FFFFFF">Menu</font></b></td>');
document.write('      </tr>');
document.write('      <tr>');
document.write('        <td width="100%" align="center"><b>');
document.write('        <font size="1" face="Trebuchet MS" color="#B23737">');
document.write('        <a href="http://www.cafeshops.com/freeformfrog/cp/subscribe_popup.aspx?s=freeformfrog" target="_blank" style="text-decoration: none">');
document.write('        <font color="#B23737">Subscribe to the newsletter</font></a></font></b><br>');
document.write('        <b><font size="1" face="Trebuchet MS" color="#B23737">');
document.write('        <a href="http://www.cafeshops.com/freeformfrog/cp/feedback_popup.aspx" target="_blank" style="text-decoration: none">');
document.write('        <font color="#B23737">Give us your feedback</font></a></font></b></td>');
document.write('      </tr>');
document.write('    </table>');
