//ranquotedom Image Script - The-Spot.net
var ranquoteimg = 266
day = new Date()
seed = day.getTime()
ran = parseInt(((seed - (parseInt(seed/1000,10) * 1000))/10)/100 * ranquoteimg + 1,10)

if (ran == (1)) ranquote = ('Almost as weird as a hippie on Prozac.')
if (ran == (2)) ranquote = ('Preferred 9 out of 10 times over Spam.')
if (ran == (3)) ranquote = ('We\'re vinegar in your baking soda.')
if (ran == (4)) ranquote = ('Bubba likes it...')
if (ran == (5)) ranquote = ('As seen on TV.')
if (ran == (6)) ranquote = ('Seen in more places than Dust Bunnies.')
if (ran == (7)) ranquote = ('Almost as hot as an Artic Summer.')
if (ran == (8)) ranquote = ('Almost as cheap as your ex-boyfriend.')
if (ran == (9)) ranquote = ('Almost as formal as a flock of penguins in Antarctica.')
if (ran == (10)) ranquote = ('Batteries not included.')
if (ran == (11)) ranquote = ('Almost as technical as Bill Gates in the Matrix.')
if (ran == (12)) ranquote = ('Where 5 out of 10 agree we have the answers.')
if (ran == (13)) ranquote = ('Almost as British as Austin Powers in Sense and Sensibility.')
if (ran == (14)) ranquote = ('Our other job requires a psychiatric ward.')
if (ran == (15)) ranquote = ('Almost as tiring as a Ben Stein on Nyquil.')
if (ran == (16)) ranquote = ('Almost as shocking as Aunt Ruthie\'s Goulash.')
if (ran == (17)) ranquote = ('We put the "fun" in dysfunctional.')
if (ran == (18)) ranquote = ('Almost as bogus as Mr. Bean in Mission: Impossible.')
if (ran == (19)) ranquote = ('Almost as emotional as a Dragonball Z episode.')
if (ran == (20)) ranquote = ('Almost as useful as a compass at the North Pole.')
if (ran == (21)) ranquote = ('Almost as useless as a flyer on a telephone pole on a Houston Freeway.')
if (ran == (22)) ranquote = ('Almost as friendly as Mr. Roger\'s Neighborhood.')
if (ran == (23)) ranquote = ('Our nickels are worth just as much as yours.')
if (ran == (24)) ranquote = ('Almost as re-run as I Love Lucy.')
if (ran == (25)) ranquote = ('Almost as blatant as Saturday Morning Cartoons.')
if (ran == (26)) ranquote = ('Almost as entertaining as Friday night in Marshall, TX.')
if (ran == (27)) ranquote = ('Almost as perfect as Bill Clinton on steroids.')
if (ran == (28)) ranquote = ('Almost as intoxicating as an insomniac playing Unreal Tournament.')
if (ran == (29)) ranquote = ('Almost as frightening as Barney on a GI Joe Cartoon.')
if (ran == (30)) ranquote = ('Almost as thrilling as a one-way trip to Granquotedma\'s house.')
if (ran == (31)) ranquote = ('Almost as exciting as Bob Dole on Viagra.')
if (ran == (32)) ranquote = ('We still think legos are da\' bomb.')
if (ran == (33)) ranquote = ('We go down like a bottle of Drain-o.')
if (ran == (34)) ranquote = ('We want a vote of No-Confidence for Spam.')
if (ran == (35)) ranquote = ('Where midgets run rampant.')
if (ran == (36)) ranquote = ('Everybody and their gerbil know about it.')
if (ran == (37)) ranquote = ('Idiot Proof.')
if (ran == (38)) ranquote = ('Proud sponsors of Sticky-Tak.')
if (ran == (39)) ranquote = ('We wouldn’t do it for all the dog meat in Korea.')
if (ran == (40)) ranquote = ('We don\'t call it "dancing," we call it "interpretive movements."')
if (ran == (41)) ranquote = ('We don\'t use big words when diminutive ones will suffice.')
if (ran == (42)) ranquote = ('640K ought to be enough for anybody.')
if (ran == (43)) ranquote = ('I don\'t know what WW3 will be like but WW4 will be of sticks and stones.')
if (ran == (44)) ranquote = ('Where few women admit their age...few men act theirs.')
if (ran == (45)) ranquote = ('Energizer Bunny Arrested! Charged with battery.')
if (ran == (46)) ranquote = ('Save the whales, collect the whole set!')
if (ran == (47)) ranquote = ('We won’t rise to the occasion, but we\'ll slide over to it.')
if (ran == (48)) ranquote = ('We used to have a handle on life, and then it broke.')
if (ran == (49)) ranquote = ('Okay, who put a stop payment on our reality check?')
if (ran == (50)) ranquote = ('A little work, a little sleep, a little love and it is all over.')
if (ran == (51)) ranquote = ('Where C++ should have been called B.')
if (ran == (52)) ranquote = ('Give us ambiguity or give us something else.')
if (ran == (53)) ranquote = ('Make it idiot proof and someone will make a better idiot.')
if (ran == (54)) ranquote = ('Ever notice how fast Windows runs?  Neither did we.')
if (ran == (55)) ranquote = ('We don\'t suffer from insanity...We enjoy every minute of it.')
if (ran == (56)) ranquote = ('Calvin, we will not have an anatomically correct snowman!')
if (ran == (57)) ranquote = ('Where He who laughs last thinks slowest!')
if (ran == (58)) ranquote = ('Hard work has a future payoff.  Laziness pays off now.')
if (ran == (59)) ranquote = ('Don\'t take life too seriously, you won\'t get out alive.')
if (ran == (60)) ranquote = ('We have enough youth, how about a fountain of SMART?')
if (ran == (61)) ranquote = ('Apple copyright 6024 b.c., Adam & Eve.')
if (ran == (62)) ranquote = ('Careful...We don\'t want to learn from this.')
if (ran == (63)) ranquote = ('Where a flashlight is a case for holding dead batteries.')
if (ran == (64)) ranquote = ('What is a free gift? Aren\'t all gifts free?')
if (ran == (65)) ranquote = ('Where change is inevitable, except from a vending machine.')
if (ran == (66)) ranquote = ('We are born naked, wet and hungry.  Then things get worse.')
if (ran == (67)) ranquote = ('Lottery: "A tax on people who are bad at math."')
if (ran == (68)) ranquote = ('Beam me aboard, Scotty..."Sure.  Will a 2x10 do?"')
if (ran == (69)) ranquote = ('Very funny, Scotty. Now beam down my clothes.')
if (ran == (70)) ranquote = ('Consciousness: that annoying time between naps.')
if (ran == (71)) ranquote = ('Double your drive space - delete Windows!')
if (ran == (72)) ranquote = ('The gene pool could use a little chlorine.')
if (ran == (73)) ranquote = ('C program run.  C program crash.  C programmer quit.')
if (ran == (74)) ranquote = ('Pentiums melt in your PC, not in your hand.')
if (ran == (75)) ranquote = ('There\'s too much blood in our caffeine system.')
if (ran == (76)) ranquote = ('Where it\'s better to understand a little than to misunderstand a lot.')
if (ran == (77)) ranquote = ('Where Criminal Lawyer is a redundancy.')
if (ran == (78)) ranquote = ('Apple Copyright 1767, Sir Isaac Newton.')
if (ran == (79)) ranquote = ('Build a watch in 179 easy steps.')
if (ran == (80)) ranquote = ('I.R.S.: "We\'ve got what it takes to take what you\'ve got!"')
if (ran == (81)) ranquote = ('Where Artificial Intelligence usually beats real stupidity.')
if (ran == (82)) ranquote = ('Oops. Our brain just hit a bad sector.')
if (ran == (83)) ranquote = ('When there\'s a will, we want to be in it.')
if (ran == (84)) ranquote = ('Where COINCIDENCE happens.')
if (ran == (85)) ranquote = ('Always remember you\'re unique, just like everyone else.')
if (ran == (86)) ranquote = ('Beulah, peel us a grape.')
if (ran == (87)) ranquote = ('Daddy, why doesn\'t this magnet pick up this floppy disk?')
if (ran == (88)) ranquote = ('Warning: Dates in Calendar are closer than they appear.')
if (ran == (89)) ranquote = ('We aren\'t complete idiots, just some parts are missing!')
if (ran == (90)) ranquote = ('Puritanism: The haunting fear that someone somewhere may be happy.')
if (ran == (91)) ranquote = ('All generalizations are false, including this one.')
if (ran == (92)) ranquote = ('Where 93% of all statistics are made up.')
if (ran == (93)) ranquote = ('Where a lot of people mistake a short memory for a clear conscience.')
if (ran == (94)) ranquote = ('We don\'t want the world...We just want your half.')
if (ran == (95)) ranquote = ('We could never sleep our way to the top, because our alarm clock always wakes us right up.')
if (ran == (96)) ranquote = ('We can lead a ferret to water but we cannot make it drink.')
if (ran == (97)) ranquote = ('Where time flies like an arrow, but fruit flies like a banana.')
if (ran == (98)) ranquote = ('You can call us anything you like but don\'t call us late for dinner.')
if (ran == (99)) ranquote = ('Now Open.  All Day, Everyday.')
if (ran == (100)) ranquote = ('Life is tough. It\'s tougher if you\'re stupid.')
if (ran == (101)) ranquote = ('Anything less would be uncivilized.')
if (ran == (102)) ranquote = ('Looks better than your girlfriend.')
if (ran == (103)) ranquote = ('We are only narcoleptic when we try to do homework.')
if (ran == (104)) ranquote = ('What is the probability that something will happen according to the odds?')
if (ran == (105)) ranquote = ('If vegetarians eat vegetables, what do humanitarians eat?')
if (ran == (106)) ranquote = ('Why is the word abbreviated so long?')
if (ran == (107)) ranquote = ('Is there a Dr. Salt?')
if (ran == (108)) ranquote = ('If Fed Ex and UPS were to merge, would the implosion be imminent?')
if (ran == (109)) ranquote = ('If a mute child swears, does his mother make him wash his hands with soap?')
if (ran == (110)) ranquote = ('If you try to fail, and succeed, which have you done?')
if (ran == (111)) ranquote = ('Why do we play in recitals and recite in plays?')
if (ran == (112)) ranquote = ('Almost as strange as a drunk mime.')
if (ran == (113)) ranquote = ('We stick to Teflon.')
if (ran == (114)) ranquote = ('If an invisible man hits a mime, how do we know the mime isn’t acting?')
if (ran == (115)) ranquote = ('Where the chat room is always room temperature.')
if (ran == (116)) ranquote = ('We put our pants on both legs at a time.')
if (ran == (117)) ranquote = ('Adapt…')
if (ran == (118)) ranquote = ('Resistance is futile!')
if (ran == (119)) ranquote = ('…or else!')
if (ran == (120)) ranquote = ('We changed out minds…they work a lot better now.')
if (ran == (121)) ranquote = ('To conform is to deform.')
if (ran == (122)) ranquote = ('It takes great thinking, and work to keep from working.')
if (ran == (123)) ranquote = ('We are dumb, but yet, we are not so dumb.')
if (ran == (124)) ranquote = ('Like Butter on a bald monkey.')
if (ran == (125)) ranquote = ('Sunshine on my shoulders makes me happy. Scalding coffee, on the other hand, does not.')
if (ran == (126)) ranquote = ('I never apologize. I\'m sorry but that is the way I am.')
if (ran == (127)) ranquote = ('We put the "ow" in "now."')
if (ran == (128)) ranquote = ('Our tongue is massive.')
if (ran == (129)) ranquote = ('Be anti-sucky.')
if (ran == (130)) ranquote = ('We\'re groovy.')
if (ran == (131)) ranquote = ('Get a duck.')
if (ran == (132)) ranquote = ('We\'re an epitome.')
if (ran == (133)) ranquote = ('We knows our ABC\'s.')
if (ran == (134)) ranquote = ('We\'re the big cheese.')
if (ran == (135)) ranquote = ('Don’t be a rhizopus Niger.')
if (ran == (136)) ranquote = ('We\'re hairy.')
if (ran == (137)) ranquote = ('Free Wynona. Lock up RIAA.')
if (ran == (138)) ranquote = ('We\'re aerodynamic.')
if (ran == (139)) ranquote = ('Be da\' bomb.')
if (ran == (140)) ranquote = ('We have great oral hygiene.')
if (ran == (141)) ranquote = ('Win free cashews.')
if (ran == (142)) ranquote = ('The Easter bunny advocates our reform.')
if (ran == (143)) ranquote = ('Support the Syrian beavers.')
if (ran == (144)) ranquote = ('We can turn fuscia at will.')
if (ran == (145)) ranquote = ('Don’t be made of latex.')
if (ran == (146)) ranquote = ('Preserve the use of "o" in the English language.')
if (ran == (147)) ranquote = ('Our middle name is "Long".')
if (ran == (148)) ranquote = ('Dirt rocks.')
if (ran == (149)) ranquote = ('Be cool like that.')
if (ran == (150)) ranquote = ('Feel the vibes.')
if (ran == (151)) ranquote = ('Also awarded MVP of last year\'s World Series.')
if (ran == (152)) ranquote = ('Back to the 50\'s.')
if (ran == (153)) ranquote = ('Back to Chernobyl.')
if (ran == (154)) ranquote = ('We\'re made in America.')
if (ran == (155)) ranquote = ('Two plus two IS four.')
if (ran == (156)) ranquote = ('We can spell.')
if (ran == (157)) ranquote = ('We\'re smoothness in a can.')
if (ran == (158)) ranquote = ('Our real name is Obi-Wan.')
if (ran == (159)) ranquote = ('We\'ve been to Crabby Bill\'s.')
if (ran == (160)) ranquote = ('Do NOT give in to the dark side.')
if (ran == (161)) ranquote = ('Be an electric Scotsman.')
if (ran == (162)) ranquote = ('We\'ve got a disc.')
if (ran == (163)) ranquote = ('We don\'t put DDT in our oatmeal.')
if (ran == (164)) ranquote = ('Judgment day is coming.')
if (ran == (165)) ranquote = ('Cows WILL jump over the moon.')
if (ran == (166)) ranquote = ('Don’t risk being lacerated.')
if (ran == (167)) ranquote = ('We exist as a solid, liquid, gas, and occasionally plasma.')
if (ran == (168)) ranquote = ('Our right foot is covered in pecans.')
if (ran == (169)) ranquote = ('We have opposable digits.')
if (ran == (170)) ranquote = ('We play the banjo.')
if (ran == (171)) ranquote = ('We own 24 out of 50 Bazooka Joe comics.')
if (ran == (172)) ranquote = ('We know where you live.')
if (ran == (173)) ranquote = ('We have pens.')
if (ran == (174)) ranquote = ('We get our daily allowance of riboflavin.')
if (ran == (175)) ranquote = ('Our voice can travel faster than Mach 1.')
if (ran == (176)) ranquote = ('Trees have feelings too.')
if (ran == (177)) ranquote = ('We\'re getting you out of class.')
if (ran == (178)) ranquote = ('We\'ve got our dancing shoes on.')
if (ran == (179)) ranquote = ('We know what we\'ve got.')
if (ran == (180)) ranquote = ('We\'re clean.')
if (ran == (181)) ranquote = ('We\'re homogenized.')
if (ran == (182)) ranquote = ('Image is nothing; thirst is everything.')
if (ran == (183)) ranquote = ('Once is never enough.')
if (ran == (184)) ranquote = ('This is not a test.')
if (ran == (185)) ranquote = ('We\'re 100% recyclable.')
if (ran == (186)) ranquote = ('We\'re shiny.')
if (ran == (187)) ranquote = ('We\'re coming behind the Hale-Bop comet.')
if (ran == (188)) ranquote = ('We\'re poly saturated.')
if (ran == (189)) ranquote = ('We\'re fruity.')
if (ran == (190)) ranquote = ('It’s the 11th amendment.')
if (ran == (191)) ranquote = ('We\'re one tough cookie.')
if (ran == (192)) ranquote = ('We\'re smarter than the average bear.')
if (ran == (193)) ranquote = ('Packed with peanuts.')
if (ran == (194)) ranquote = ('There’s nothing in our chicken but chicken.')
if (ran == (195)) ranquote = ('We\'ve gotta have our Pops.')
if (ran == (196)) ranquote = ('Free the Cubans.')
if (ran == (197)) ranquote = ('Steak with A1 sauce.')
if (ran == (198)) ranquote = ('We like the Big Bad Beetleborgs.')
if (ran == (199)) ranquote = ('We\'re a good goalie.')
if (ran == (200)) ranquote = ('We were on death row.')
if (ran == (201)) ranquote = ('We swim with the dolphins.')
if (ran == (202)) ranquote = ('We\'re the Spice Girls.')
if (ran == (203)) ranquote = ('Now with 25% more cleaning power.')
if (ran == (204)) ranquote = ('We\'re USDA approved.')
if (ran == (205)) ranquote = ('Strong enough for a man, but pH balanced for a woman.')
if (ran == (206)) ranquote = ('We know how to get down.')
if (ran == (207)) ranquote = ('Maybe we\'ll go away.')
if (ran == (208)) ranquote = ('Save bacon from national persecution.')
if (ran == (209)) ranquote = ('For the heck of it.')
if (ran == (210)) ranquote = ('We\'re not synthetic.')
if (ran == (211)) ranquote = ('Chicken farmers love us.')
if (ran == (212)) ranquote = ('We\'re Zest-fully clean.')
if (ran == (213)) ranquote = ('Obey your mother.')
if (ran == (214)) ranquote = ('We made "w" a standard algebraic variable.')
if (ran == (215)) ranquote = ('‘Cause stuff happens.')
if (ran == (216)) ranquote = ('We\'re not the bad guy.')
if (ran == (217)) ranquote = ('We\'re feeling fat and sassy.')
if (ran == (218)) ranquote = ('Our spoon is too big.')
if (ran == (219)) ranquote = ('I\'m a banana.')
if (ran == (220)) ranquote = ('There\'s nothin\' in our chicken, but chicken.')
if (ran == (221)) ranquote = ('We learned not to get our SuperCard signed in 4th grade.')
if (ran == (222)) ranquote = ('We got a new bike.')
if (ran == (223)) ranquote = ('Our feelings are easily hurt when someone starts punching us.')
if (ran == (224)) ranquote = ('We get to write anything we want...like spelling words!')
if (ran == (225)) ranquote = ('If shoes could talk...')
if (ran == (226)) ranquote = ('We have daymares.')
if (ran == (227)) ranquote = ('Where Ninja Turtles are still cool.')
if (ran == (228)) ranquote = ('Not your grandmother\'s website.')
if (ran == (229)) ranquote = ('With the full financial backing of the Tooth Fairy.')
if (ran == (230)) ranquote = ('We dug the ocean.')
if (ran == (231)) ranquote = ('For shiggle, my wiggle.')
if (ran == (232)) ranquote = ('Normal people drink water. Smart people sell it.')
if (ran == (233)) ranquote = ('We flashmob in Tyler, TX.')
if (ran == (234)) ranquote = ('The government supplies our staples.')
if (ran == (235)) ranquote = ('We peed in your pool.')
if (ran == (236)) ranquote = ('We\'ve collected 1000 empty tuna cans.')
if (ran == (237)) ranquote = ('We feed the rich.')
if (ran == (238)) ranquote = ('Got BAWLS?')
if (ran == (239)) ranquote = ('We have lots of BAWLS.')
if (ran == (240)) ranquote = ('Leggo our eggo.')
if (ran == (241)) ranquote = ('Vote straight ticket, even if you\'re gay.')
if (ran == (242)) ranquote = ('Vote for Bush!')
if (ran == (243)) ranquote = ('The <i>virtually</i> <u>real thing</u>!')
if (ran == (244)) ranquote = ('I love you baby, but I just can\'t smile.')
if (ran == (245)) ranquote = ('Oops..I farkled.')
if (ran == (246)) ranquote = ('The lights are off, and everyone\'s home.')
if (ran == (247)) ranquote = ('Soy de la gente!')
if (ran == (248)) ranquote = ('Shower clothed. It saves laundry money.')
if (ran == (249)) ranquote = ('You should see our <i>Diet</i> site.')
if (ran == (250)) ranquote = ('We are not amused.')
if (ran == (251)) ranquote = ('No MSG.')
if (ran == (252)) ranquote = ('We\'re feeling thin and snippy.')
if (ran == (253)) ranquote = ('Clean Dirt!')
if (ran == (254)) ranquote = ('It\'s not easy being cheesy.')
if (ran == (255)) ranquote = ('Stupidity Unscripted.')
if (ran == (256)) ranquote = ('We have a biopoly on air and water.')
if (ran == (257)) ranquote = ('What is the problem with people who ask sarcastic rhetorical questions?')
if (ran == (258)) ranquote = ('The thing that sucks most about not having lips is the fact that you can\'t.')
if (ran == (259)) ranquote = ('If you know what we mean...')
if (ran == (260)) ranquote = ('No matter which way you slice it, you\’ve sliced it. And it won\'t grow back. Way to not pay attention, idiot.')
if (ran == (261)) ranquote = ('NEXT time, we\'ll use Borax!')
if (ran == (262)) ranquote = ('As spoken in the prophecies.')
if (ran == (263)) ranquote = ('More fun than recreational pharmecuticals.')
if (ran == (264)) ranquote = ('The only thing we can\'t make is sense.')
if (ran == (265)) ranquote = ('We always have something to say...sometimes.')
if (ran == (266)) ranquote = ('Changing sleeping habbits everywhere.')

document.write(ranquote + '<br><font size="1"><b>QuickQuip #' + ran + ' of ' + ranquoteimg + '</b></font>');
